---
  - name: Install Packages
    apt:
      force: yes
      update_cache: yes                
      name: "{{ prerequirements_packages }}" 
      autoclean: yes 
      purge: yes
      state: present        
      install_recommends: yes
      
  - name: Add an Apt signing key, uses whichever key is at the URL
    shell: curl -sL "{{ item.value.url }}" | bash -
    with_dict:
      - "{{ repository_key }}"

  - name: Install Packages
    apt:
      force: yes
      update_cache: yes                
      name: "{{ required_packages }}" 
      autoclean: yes 
      purge: yes
      state: present        
      install_recommends: yes    
